---
title: "Problem Set 7"
output: html_document
date: "11/18/2018"
author: Cayanne Chachati and Ghada Amer 
---

```{r setup, include=FALSE, error = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(ggplot2)
library(kableExtra)
library(rebus)
library(lubridate)
library(knitr)
library(haven)
library(scales)
library(fs)
library(janitor)
library(moderndive)
library(pspearman)
library(ggpubr)
```

```{r echo = FALSE,  error = FALSE, message = FALSE, warning = FALSE}

  ## Automate the process of downloading and unzipping files 

download.file("https://goo.gl/ZRCBda","poll.zip", quiet = TRUE)
unzip("poll.zip")

file_names <- dir_ls("2018-live-poll-results-master/data")

  ## Use the map_df function to read all the files.
  ## Specify .id = source to display the source or file name next to each observation.
  ## Using str_remove_all, remove the beginning of all source names,
  ## only keeping the end part that distinguishes different files.
  ## This will make it easier to deal with the file names in the future. 

data <- map_df(file_names, read_csv, .id = "source") %>%
  mutate(source = str_remove_all(source, pattern = "2018-live-poll-results-master/data/elections-poll-"))

data
```

```{r}
forecast <-
  data %>%
  mutate(office_district = str_sub(source, 3, -7)) %>%
  mutate(office_district = str_remove(office_district, "^0+")) %>%

  
  mutate(state = str_sub(source, 1, 2)) %>%
  mutate(wave = str_sub(source, -5, -5))

forecast <-
forecast %>%
  filter(office_district != "gov" & office_district != "sen") %>%
  mutate(state = str_to_upper(state)) %>%
  unite(district, c("state", "office_district"), sep = "-") %>% 
  mutate(response = case_when(
           response == "Dem" ~ "Dem",
           response == "Rep" ~ "Rep",
           response == "Und" ~ "Und", 
           response == "3" ~ "3",
           response == "4" ~ "4",
           response == "5" ~ "5")) 

forecast_once <- 
  forecast %>%
  group_by(district) %>%
  mutate(distinct = n_distinct(wave)) %>%
  filter(distinct == 1)

  
forecast_twice <- 
  forecast %>%
  group_by(district) %>%
  mutate(distinct = n_distinct(wave)) %>%
  filter(distinct == 2) %>%
  filter(wave == 3)

latest <- 
  bind_rows(forecast_once, forecast_twice) %>%
  select(district, response, ager, final_weight, educ, race_eth)


latest_adv_rep <- 
  latest %>%
  group_by(district, response) %>% 
  count(wt = final_weight) %>% 
  spread(response, n, fill = 0) %>% 
  mutate(all = Dem + Rep + Und + `3` + `4` + `5`) %>% 
  mutate(adv_rep = ((Rep - Dem)/all)) %>%
  adorn_pct_formatting(digits=0) %>%
  select(district, adv_rep)
```

```{r}
educ <-
  latest %>%
  filter(!educ %in% c("[DO NOT READ] Don't know/Refused", "[DO NOT READ] Refused")) %>%
  group_by(district, educ) %>%
  count(wt = final_weight) %>%
  ungroup()

educ <-
  educ %>%
  group_by(district) %>%
  mutate(sum = sum(n)) %>%
  ungroup()

educ <- 
  educ %>%
  group_by(district, educ) %>%
  mutate(percentage = n/sum) %>%
  select(district, educ, percentage) %>%
  adorn_pct_formatting(digits=0)


join_educ <-
  left_join(educ, latest_adv_rep, by = "district") %>%
  mutate(percentage = parse_number(percentage),
         adv_rep = parse_number(adv_rep))

plot_educ <- 
join_educ %>%
  ggplot(aes(x = percentage, y = adv_rep)) + geom_jitter() +
  geom_smooth(method = lm, se= FALSE) + facet_wrap(~educ) + theme_light() + 
  labs(x = "Percentage of Responds in each Education", y = "Advantage Republican")

plot_educ + stat_cor(method = "pearson", label.x = 3, label.y = 20, size = 3, output.type = "text")

```

```{r}
age <-
  latest %>%
  filter(!ager %in% c("[DO NOT READ] Don't know/Refused", "[DO NOT READ] Refused")) %>%
  group_by(district, ager) %>%
  count(wt = final_weight) %>%
  ungroup()

age <-
  age %>%
  group_by(district) %>%
  mutate(sum = sum(n)) %>%
  ungroup()

age <- 
  age %>%
  group_by(district, ager) %>%
  mutate(percentage = n/sum) %>%
  select(district, ager, percentage) %>%
  adorn_pct_formatting(digits=0)


join_age <-
  left_join(age, latest_adv_rep, by = "district") %>%
  mutate(percentage = parse_number(percentage),
         adv_rep = parse_number(adv_rep))

plot_age <- 
join_age %>%
  ggplot(aes(x = percentage, y = adv_rep)) + geom_jitter() +
  geom_smooth(method = lm, se= FALSE) + facet_wrap(~ager) + theme_light(base_size = 11) + 
  labs(x = "Percentage of Responds in each Education", y = "Advantage Republican")

plot_age + stat_cor(method = "pearson", label.x = 3, label.y = 20, size = 3, output.type = "text")

```

```{r}
race <-
  latest %>%
  filter(!race_eth %in% c("[DO NOT READ] Don't know/Refused")) %>%
  group_by(district, race_eth) %>%
  count(wt = final_weight) %>%
  ungroup()

race <-
  race %>%
  group_by(district) %>%
  mutate(sum = sum(n)) %>%
  ungroup()

race <- 
  race %>%
  group_by(district, race_eth) %>%
  mutate(percentage = n/sum) %>%
  select(district, race_eth, percentage) %>%
  adorn_pct_formatting(digits=0)


join_race <-
  left_join(race, latest_adv_rep, by = "district") %>%
  mutate(percentage = parse_number(percentage),
         adv_rep = parse_number(adv_rep))


plot_race <- 
join_race %>%
  ggplot(aes(x = percentage, y = adv_rep)) + geom_jitter(width = 5) +
  geom_smooth(method = lm, se= FALSE) + facet_wrap(~race_eth) + theme_light(base_size = 11) + 
  labs(title = "hello",
       x = "Percentage of Responds in each Education", y = "Advantage Republican")

plot_race + stat_cor(method = "pearson", label.x = 3, label.y = 20, size = 3, output.type = "text")


```



forecast_new <-
  forecast %>% 
  group_by(district, wave, response) %>% 
  count(wt = final_weight) %>% 
  spread(response, n, fill = 0) %>% 
  mutate(all = Dem + Rep + Und + `3` + `4` + `5`) %>% 
  mutate(adv_rep = ((Rep - Dem)/all)) %>% 
  select(district, wave, adv_rep) %>% 
  adorn_pct_formatting(digits=0)

forecast_new 
  
```
=



```
